# Generated by Django 3.0.6 on 2021-07-16 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this director', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of director', max_length=64, unique=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this movie', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of movie', max_length=256)),
                ('run_time', models.IntegerField(null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Director')),
            ],
        ),
    ]
