# Generated by Django 3.0.6 on 2021-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wombat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('shootable', models.BooleanField(default=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('speed', models.FloatField(default=0.0)),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
