# Generated by Django 3.0.6 on 2021-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wombats', '0002_wombat_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='wombat',
            name='attitude',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
