# Generated by Django 3.0.6 on 2021-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wombats', '0003_wombat_attitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wombat',
            name='attitude',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wombat',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
