# Generated by Django 3.0.6 on 2021-07-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20171112_1946'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='band',
            order_with_respect_to=None,
        ),
    ]
